#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=98

start() {
  if [ -f "/dev/mmcblk0p1" ]; then
    mkdir -p /mnt/sd
    mount -t vfat /dev/mmcblk0p1 /mnt/sd
    # udevd --daemon
    # udevstart
  fi
}
