language: c

addons:
  apt:
    packages:
    - gdb

os:
  - linux
  - osx

before_script:
  - ulimit -c unlimited -S
  - source .travis/platform.sh
  - if [[ ${PLATFORM} == linux ]]; then source .travis/setenv_lua.sh; fi
  - if [[ ${PLATFORM} == linux ]]; then luarocks install luacov-coveralls --server=https://luarocks.org/dev; fi
  - if [[ ${PLATFORM} == linux ]]; then export LUA_PATH=`luarocks path --lr-path`; fi

script:
  - RESULT=0
  - make
  - if [[ ${PLATFORM} == linux ]]; then make cover || RESULT=$?; else  make test || RESULT=$?; fi
  - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd) core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done
  - if [[ ${RESULT} != 0 ]]; then exit $RESULT ; fi
  - if [[ ${PLATFORM} == linux ]]; then luacov-coveralls; fi

notifications:
  email: true
  irc: "irc.freenode.org#luvit"

env:
  global:
    - LUAROCKS=3.3.1
    - LUA=luajit2.1  # current head of 2.1 branch
    - secure: pQr0Jc5N3CIWyGn8JmH/2C1AbKTmTJvJfQgVJMuhZjFzU3wHG5U2Opjgbs2kGeijvevCI2UDhw1l0M28kqvxM0tmi3JSLHKPbbV0aaqJpATUbVa6BSCnsFvl7ZKn3oLlPPS/VdHPXM10KrZGMCWGy2zLWn84n14rMwKflAYFrQE=
