#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=app
PROG=/usr/bin/t2n

start_service() {
	procd_open_instance
	procd_set_param respawn
	procd_set_param command "$PROG" -r -a dhcp:0.0.0.0 -k 12345678 -u 8618991839321 -c 1234 -l 106.12.253.52:6050 -D /dev/ttyUSB1 -W 37 -v -v -v
	procd_close_instance
}

stop() {
	service_stop "$PROG"
}

reload() {
	service_reload "$PROG"
}
