#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=app
PROG=/root/app/run

start_service() {
	procd_open_instance
	procd_set_param respawn
	procd_set_param command /bin/sh "$PROG" /root/app/ub_cors.lua
	procd_close_instance
}

stop() {
	service_stop "$PROG"
}

reload() {
	service_reload "$PROG"
}
